{
 "title": "Intensive Care Troubleshooting",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "SR Linux On change CPU Custom Threshold (80%) Monitoring",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "alias": "$tag_source",
     "groupBy": [
      { "params": [ "source" ], "type": "tag" }
     ],
     "measurement": "SRL_docter-agent-cpu",
     "select": [
      [
       {
        "params": [
         "/docter_agent:docter_agent/metrics/metric_status"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Topology View",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "status-detail-leaf1",
     "measurement": "SRL_docter-agent-cpu",
     "select": [
      [
       {
        "params": [
         "/docter_agent:docter_agent/metrics/metric_status"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "clab-srl-docter-lab-leaf1" }
     ]
    },
    {
     "alias": "status-detail-leaf2",
     "measurement": "SRL_docter-agent-cpu",
     "select": [
      [
       {
        "params": [
         "/docter_agent:docter_agent/metrics/metric_status"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "clab-srl-docter-lab-leaf2" }
     ]
    },
    {
     "alias": "status-detail-leaf3",
     "measurement": "SRL_docter-agent-cpu",
     "select": [
      [
       {
        "params": [
         "/docter_agent:docter_agent/metrics/metric_status"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "clab-srl-docter-lab-leaf3" }
     ]
    }
   ]
  },
  {
   "title": "Traditional Monitoring (sample interval:20s)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gnmic_srl_cpu_instant{}" }
   ]
  },
  {
   "title": "CPU per process",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "measurement": "SRL_docter-agent-cpu",
     "query": "SELECT \"source\" AS \"Node\", \"/docter_agent:docter_agent/metrics/metric/contribution_reports_2\" AS \"CPU %\" FROM \"SRL_docter-agent-cpu\" WHERE $timeFilter",
     "select": [
      [
       {
        "params": [
         "/docter_agent:docter_agent/metrics/metric/contribution_reports_1"
        ],
        "type": "field"
       },
       { "params": [ "CPU %" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latest Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "measurement": "SRL_docter-agent-cpu",
     "query": "SELECT \"source\" AS \"Node\", \"/docter_agent:docter_agent/metrics/metric_status-summary\" AS \"Status\" FROM \"SRL_docter-agent-cpu\" WHERE $timeFilter limit 3",
     "select": [
      [
       {
        "params": [
         "/docter_agent:docter_agent/metrics/metric_status-summary"
        ],
        "type": "field"
       },
       { "params": [ "Status" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Status History",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "measurement": "SRL_docter-agent-cpu",
     "query": "SELECT \"source\" AS \"Node\",  \"/docter_agent:docter_agent/metrics/metric_status-summary\" AS \"Consolidated State\" FROM \"SRL_docter-agent-cpu\" WHERE $timeFilter",
     "select": [
      [
       {
        "params": [
         "/docter_agent:docter_agent/metrics/metric_cause"
        ],
        "type": "field"
       },
       { "params": [ "Cause" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "/docter_agent:docter_agent/metrics/metric/contribution_status"
        ],
        "type": "field"
       },
       { "params": [ "Status" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "/docter_agent:docter_agent/metrics/metric_status-summary"
        ],
        "type": "field"
       },
       { "params": [ "Status" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}