# config file version
apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    url: http://clab-auto-frr-evpn-lab-influxdb:8086
    database: gnmic
    
  - name: Prometheus
    type: prometheus
    url: http://clab-auto-frr-evpn-lab-prometheus:9090
